/*
 * The MIT License
 *
 * Copyright 2015 mazuh.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package br.com.fanex.mazuh.janelas.instrutores;

import br.com.fanex.mazuh.acesso.Sessao;
import br.com.fanex.mazuh.edu.Exercicio;
import br.com.fanex.mazuh.jpa.ExercicioJpaController;
import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.JOptionPane;

/**
 *
 * @author mazuh
 */
public class Exercicio_Corrigir extends javax.swing.JFrame {

    private static Exercicio exercicio;
    
    /**
     * Creates new form Exercicio_Corrigir
     * @param exercicio
     */
    public Exercicio_Corrigir(Exercicio exercicio) {
        Exercicio_Corrigir.exercicio = exercicio;
        
        // configura form
        initComponents();
        
        this.setTitle("[CORREÇÃO] " + exercicio.toString());
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        // setters nos JLabel
        jExercicio.setText("(ID " + exercicio.getId() + ") " + exercicio.toString());
        jAluno.setText(exercicio.getIdAluno().toString());
        
        txtRespostas.setText(exercicio.getRespostas());
    }
    
    /*
    Insere uma lista vazia numerada. A quantidade de itens irá variar de acordo
    com o digitado no jspinner.
    Depois o focus é requisitado ao textarea de correção.
    Se o valor do jspinner for menor que 0, ele será 0.
    */
    private void inserirNumeracao(){
        int numeracao = (Integer) jNumeracao.getValue();
        
        if (numeracao > 0){
            
            for (int i = 1; i <= numeracao; i++)
                txtCorrecao.setText(txtCorrecao.getText() + "\n" + i + " - ");
            txtCorrecao.requestFocus();
            
        } else{
            jNumeracao.setValue(0);
        }
        
    }

    /*
    Abre o url usando o navegador padrão.
    Emite caixas de diálogo de erro caso lance exceptions.
    ps: as mensagens estão configuradas para considerar que o link é de um gabarito.
    */
    private void abrirLink(String url){
        Desktop desktop = Desktop.getDesktop();
        
        try {
            
            desktop.browse(new URI(url)); // abre o browser no link
            
            
        } catch (IOException | URISyntaxException ioe) {
            JOptionPane.showMessageDialog(null, 
                    "O URL do gabarito não está configurado corretamente.\n"
                            + "Gerencie este curso e cheque as configurações.", 
                    "ERRO GABARITO", 
                    JOptionPane.PLAIN_MESSAGE);
            
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, 
                    "Algo errado na tentativa de abrir o gabarito.", 
                    "ERRO GABARITO", 
                    JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtRespostas = new java.awt.TextArea();
        jLabel5 = new javax.swing.JLabel();
        txtCorrecao = new java.awt.TextArea();
        btnTerminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jNumeracao = new javax.swing.JSpinner();
        btnInserirNumeracao = new javax.swing.JButton();
        btnGabarito = new javax.swing.JButton();
        jAluno = new javax.swing.JLabel();
        jExercicio = new javax.swing.JLabel();
        btnGabaritoAlt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(22, 160, 133));
        jLabel1.setText("Corrigindo Exercício de Revisão");
        jLabel1.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(22, 160, 133));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ALUNO:");
        jLabel2.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(22, 160, 133));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("EXERCÍCIO:");
        jLabel3.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(22, 160, 133));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("RESPOSTAS ESCRITAS PELO(A) ALUNO(A):");
        jLabel4.setOpaque(true);

        txtRespostas.setEditable(false);

        jLabel5.setBackground(new java.awt.Color(22, 160, 133));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CORREÇÃO DO(A) INSTRUTOR(A):");
        jLabel5.setOpaque(true);

        btnTerminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fanex/mazuh/janelas/imgs/icon/salvar.gif"))); // NOI18N
        btnTerminar.setText("Terminei de corrigir!");
        btnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel6.setText("Inserir numeração:");

        jNumeracao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jNumeracaoKeyPressed(evt);
            }
        });

        btnInserirNumeracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fanex/mazuh/janelas/imgs/icon/escrever.gif"))); // NOI18N
        btnInserirNumeracao.setText("Inserir");
        btnInserirNumeracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirNumeracaoActionPerformed(evt);
            }
        });

        btnGabarito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fanex/mazuh/janelas/imgs/icon/transferencia.gif"))); // NOI18N
        btnGabarito.setText("Ver gabarito do curso");
        btnGabarito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGabaritoActionPerformed(evt);
            }
        });

        jAluno.setText("null");

        jExercicio.setText("null");

        btnGabaritoAlt.setText("Alternativo");
        btnGabaritoAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGabaritoAltActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRespostas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCorrecao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(3, 3, 3)
                        .addComponent(jNumeracao, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInserirNumeracao))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTerminar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jAluno))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jExercicio))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGabarito)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGabaritoAlt)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnTerminar)
                    .addComponent(btnCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jAluno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jExercicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnGabarito)
                    .addComponent(btnGabaritoAlt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRespostas, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jNumeracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInserirNumeracao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCorrecao, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
    Com a devida confirmação do usuário, fecha a janela.
    */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        int resposta = JOptionPane.showConfirmDialog(null,
                "Deseja mesmo cancelar esta correção?\n"
                        + "Se você tiver digitado algo, será perdido.");
        
        if (resposta == JOptionPane.YES_OPTION)
            this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /*
    Abre o link do gabarito pelo navegador padrão.
    */
    private void btnGabaritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGabaritoActionPerformed
        abrirLink(exercicio.getIdCurso().getUrlGabarito());
    }//GEN-LAST:event_btnGabaritoActionPerformed

    /*
    Insere uma lista vazia numerada. A quantidade de itens irá variar de acordo
    com o digitado no jspinner.
    */
    private void btnInserirNumeracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirNumeracaoActionPerformed
        inserirNumeracao();
    }//GEN-LAST:event_btnInserirNumeracaoActionPerformed

    /*
    Se a tecla tab ou enter for pressionada enquanto o jspinner estiver focado,
    a numeração é inserida.
    */
    private void jNumeracaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNumeracaoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER
                || evt.getKeyCode() == KeyEvent.VK_TAB){
            inserirNumeracao();
        }
    }//GEN-LAST:event_jNumeracaoKeyPressed

    /*
    Quando a tela entrar em foco, o foco irá mudar para o jspinner de numeração.
    */
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        jNumeracao.requestFocus();
    }//GEN-LAST:event_formWindowGainedFocus

    /*
    Abre o link do gabarito alternativo usando o navegador padrão.
    */
    private void btnGabaritoAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGabaritoAltActionPerformed
        abrirLink(exercicio.getIdCurso().getUrlGabarito());
    }//GEN-LAST:event_btnGabaritoAltActionPerformed

    /*
    Caso o usuário confirme, configura objeto local e envia para a 
    persistência via DAO.
    */
    private void btnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarActionPerformed
        int resposta = JOptionPane.showConfirmDialog(null,
                "Tem certeza que deseja enviar esta correção?");
        
        if (resposta == JOptionPane.YES_OPTION) {
            
            // inicia processo de configuração de objeto local
            exercicio.setCorrecao(txtCorrecao.getText());
            exercicio.setQtdPerguntas((Integer) jNumeracao.getValue());
            exercicio.setIsCorrigido((short) 1);

            try {

                // persistência do obj local por DAO
                new ExercicioJpaController(Sessao.getEntityManagerFactory()).edit(exercicio);
                // msg de confirmação e fecha janela caso nenhuma exception tenha sido lançada
                JOptionPane.showMessageDialog(null, "Exercício corrigido com sucesso.");
                this.dispose();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,
                        "Erro ao tentar salvar no banco de dados.",
                        "ERRO",
                        JOptionPane.ERROR_MESSAGE);

            }
            
        } // else faça nada
    }//GEN-LAST:event_btnTerminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercicio_Corrigir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercicio_Corrigir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercicio_Corrigir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercicio_Corrigir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercicio_Corrigir(exercicio).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGabarito;
    private javax.swing.JButton btnGabaritoAlt;
    private javax.swing.JButton btnInserirNumeracao;
    private javax.swing.JButton btnTerminar;
    private javax.swing.JLabel jAluno;
    private javax.swing.JLabel jExercicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSpinner jNumeracao;
    private java.awt.TextArea txtCorrecao;
    private java.awt.TextArea txtRespostas;
    // End of variables declaration//GEN-END:variables
}
