/*
 * The MIT License
 *
 * Copyright 2015 mazuh.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package br.com.fanex.mazuh.janelas.instrutores;

import br.com.fanex.mazuh.acesso.Sessao;
import br.com.fanex.mazuh.acesso.Usuario;
import br.com.fanex.mazuh.edu.Exercicio;
import br.com.fanex.mazuh.janelas.Login;
import br.com.fanex.mazuh.janelas.Usuario_Preferencias;
import br.com.fanex.mazuh.janelas.alunos.Exercicio_Ver;
import br.com.fanex.mazuh.jpa.ExercicioJpaController;
import br.com.fanex.mazuh.jpa.UsuarioJpaController;
import javax.swing.JOptionPane;

/**
 *
 * @author mazuh
 */
public class Painel_Instrutor extends javax.swing.JFrame {
    
    /**
     * Creates new form Painel_Instrutor
     */
    public Painel_Instrutor() {
        initComponents();
        
        this.setTitle("Iris - Painel de Instrutor(a)");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }
    
    /*
    Abre uma caixa de diálogo para o usuário digitar um ID válido.
    
    O ID pode ser de qualquer uma das entidades de persistência.
    É feita uma checagem básica de integridade e tratamento de erro.
    Caixas de diálogo de erro podem surgir informando que o valor é inválido.
    
    Retorna -1 se algo der errado.
    Retorna o valor digitado caso ele seja válido.
    */
    private int inputValidoID(){
        int id = -1; // variável para armazenar o ID que o usuário irá digitar.
        
        // caixa de diálogo pra entrada de dados em texto.
        String entrada = JOptionPane.showInputDialog(null,
                "Digite o ID (código numérico) válido:");
        
        // botão de cancelar: retorna sinal inválido.
        if (entrada == null)
            return -1; // o return aqui evita processamentos desnecessários das linhas seguintes
        
        // botão de ok: bloco de try-catch-finally para mais verificações.
        try {
           
            // tenta converter pra inteiro
            id = Integer.valueOf(entrada);
            
        } catch (NumberFormatException e) {
            
            // erro?
            id = -1;
            
        } finally {
             
            if (id > 0){  
                // está tudo ok, retorna o id digitado em Integer.
                return id;
            
            } else{ // id é 0 ou negativo seja porque o usuário digitou assim, ou porque o catch pegou algo 
                
                // mensagenzinha de erro!
                JOptionPane.showMessageDialog(
                    null,
                    "Calma aí com esse botão de \"OK\", fera!\n"
                            + "Por favor, apenas um código numérico decimal\n"
                            + "que pertencer ao conjunto dos inteiros\n"
                            + "maiores que zero e menores que "
                            + Integer.MAX_VALUE + ".",
                   "Ops...",
                    JOptionPane.ERROR_MESSAGE);
                
                return -1; // e retorno sinalizando invalidez
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        btnBuscarAlunoPorID = new javax.swing.JButton();
        btnAlunoRecuperarSenhaPadrao = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnAtualizarExerciciosIncompletos = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnBuscarExercicioPorID = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        btnLogoff = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(22, 160, 133));
        jLabel1.setText("Bem-vindo(a), instrutor(a)");
        jLabel1.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(39, 174, 96));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ALUNOS DESTA UNIDADE");
        jLabel2.setOpaque(true);

        jButton3.setText("Listar todos");

        btnBuscarAlunoPorID.setText("Buscar por ID");
        btnBuscarAlunoPorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAlunoPorIDActionPerformed(evt);
            }
        });

        btnAlunoRecuperarSenhaPadrao.setText("Recuperar senha padrão");
        btnAlunoRecuperarSenhaPadrao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlunoRecuperarSenhaPadraoActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(39, 174, 96));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SEUS EXERCÍCIOS");
        jLabel4.setOpaque(true);

        btnAtualizarExerciciosIncompletos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fanex/mazuh/janelas/imgs/icon/pasta.gif"))); // NOI18N
        btnAtualizarExerciciosIncompletos.setText("Atualizar");

        jLabel5.setBackground(new java.awt.Color(39, 174, 96));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("EXERCÍCIOS DE REVISÃO AGUARDANDO SUA CORREÇÃO");
        jLabel5.setOpaque(true);

        jButton2.setText("Listar todos");

        btnBuscarExercicioPorID.setText("Buscar por ID");
        btnBuscarExercicioPorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarExercicioPorIDActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(39, 174, 96));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SUPORTE E CONFIGURAÇÕES");
        jLabel6.setOpaque(true);

        jButton6.setText("Alterar nome/senha");

        jButton8.setText("Fazer contato com desenvolvedor");

        jButton9.setText("Pedidos p/ imprimir");
        jButton9.setEnabled(false);

        btnLogoff.setText("Fazer logoff");
        btnLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoffActionPerformed(evt);
            }
        });

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Aluno", "Curso", "Aula", "Situação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jButton1.setText("<");

        jButton5.setText(">");

        jLabel8.setText("0");

        jLabel7.setText("Páginas:");

        jLabel3.setText("Você tem 0 exercício(s) para corrigir.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(4, 4, 4)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addGap(53, 53, 53)
                        .addComponent(btnAtualizarExerciciosIncompletos, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnAlunoRecuperarSenhaPadrao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBuscarAlunoPorID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBuscarExercicioPorID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnLogoff, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarAlunoPorID)
                    .addComponent(btnBuscarExercicioPorID)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlunoRecuperarSenhaPadrao)
                    .addComponent(jButton9)
                    .addComponent(btnLogoff))
                .addGap(43, 43, 43)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(btnAtualizarExerciciosIncompletos)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
    Retira o usuário da Sessao, fecha este painel e abre a tela de Login.
    */
    private void btnLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoffActionPerformed
            Sessao.sair();
            this.dispose();
            
            new Login().setVisible(true);
    }//GEN-LAST:event_btnLogoffActionPerformed

    /*
    Pergunta o ID que quer ser buscado e, se for válido e de um aluno, irá
    abrir a tela de preferências dele.
    */
    private void btnBuscarAlunoPorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAlunoPorIDActionPerformed
        String msg = null;
        
        try{
            // busca
            UsuarioJpaController usuarioDAO = new UsuarioJpaController(Sessao.getEntityManagerFactory());
            Usuario aluno = usuarioDAO.findUsuario(inputValidoID());
            
            // é aluno?
            if (aluno.getIdHierarquia().getNome().equalsIgnoreCase("aluno"))
                new Usuario_Preferencias(aluno).setVisible(true); // prox tela!
            else // opa
                msg = "Parece que o usuário não é um aluno.\n"
                        + "Acesso NEGADO!\n\n"
                        + "Deixe de cabimento, " + Sessao.usuario_logado().getNome();
            
        } catch(Exception e){
            // erro com DAO. Busca por id <= 0 ou falha no acesso.
            msg = "Não foi possível buscar o ID do aluno.";
        }
        
        if (msg != null){ // se houver msg, que seja exibida ao mundo!
            JOptionPane.showMessageDialog(null, msg, "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnBuscarAlunoPorIDActionPerformed

    /*
    Pergunta o ID do exercício a ser buscado e, se for válido, irá
    abrir a tela de visualização dele.
    */
    private void btnBuscarExercicioPorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarExercicioPorIDActionPerformed
        try{
            // busca
            ExercicioJpaController exercicioDAO = new ExercicioJpaController(Sessao.getEntityManagerFactory());
            Exercicio exercicio = exercicioDAO.findExercicio(inputValidoID());
            
            // próx tela
            new Exercicio_Ver(exercicio).setVisible(true);
            
        } catch(Exception e){
            // erro com DAO. Busca por id <= 0 ou falha no acesso.
            JOptionPane.showMessageDialog(null,
                    "Não foi possível buscar o ID do exercício",
                    "ERRO",
                    JOptionPane.ERROR_MESSAGE
            );
            
        }
    }//GEN-LAST:event_btnBuscarExercicioPorIDActionPerformed

    /*
    Recebe o ID de um aluno sua senha retornará para o padrão (== id).
    */
    private void btnAlunoRecuperarSenhaPadraoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlunoRecuperarSenhaPadraoActionPerformed
        String msg = null;
        
        try{
            // busca
            UsuarioJpaController usuarioDAO = new UsuarioJpaController(Sessao.getEntityManagerFactory());
            Usuario aluno = usuarioDAO.findUsuario(inputValidoID());
            
            // é aluno?
            if (aluno.getIdHierarquia().getNome().equalsIgnoreCase("aluno")){
                
                aluno.setSenha(String.valueOf(aluno.getId())); // muda senha 
                usuarioDAO.edit(aluno); // persiste
                
                // msg continua null (sem erro!)
                JOptionPane.showMessageDialog(null, "Alteração efetuada com sucesso!"
                        + "\nAluno: " + aluno.getNome()
                        + "\nNova senha: " + aluno.getSenha());
                
            }else{ // opa, não é um aluno! :o
                msg = "Parece que o usuário não é um aluno.\n"
                        + "Acesso NEGADO!\n\n"
                        + "Deixe de cabimento, " + Sessao.usuario_logado().getNome();
                
            }
        } catch(Exception e){
            // erro com DAO. Busca por id <= 0 ou falha no acesso.
            msg = "Não foi possível buscar o ID do aluno ou houve falha na tentativa"
                    + "de modificar a senha.";
        }
        
        if (msg != null){ // se houver msg, que seja exibida ao mundo!
            JOptionPane.showMessageDialog(null, msg, "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAlunoRecuperarSenhaPadraoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Painel_Instrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Painel_Instrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Painel_Instrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Painel_Instrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Painel_Instrutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlunoRecuperarSenhaPadrao;
    private javax.swing.JButton btnAtualizarExerciciosIncompletos;
    private javax.swing.JButton btnBuscarAlunoPorID;
    private javax.swing.JButton btnBuscarExercicioPorID;
    private javax.swing.JButton btnLogoff;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
